### PR TITLE
Fix build grpc

### PR DESCRIPTION
**Pull request by peci1**
Now I even succeeded building with GRPC.

### CODE REVIEW

**Comment by peci1** [comment]
Tested both CPU version and GPU CUDA 9/CUDNN 7.

**Comment by 130s** [comment]
+1. We've confirmed this change lets the package build on Ubuntu Xenial (ref. our fork https://github.com/plusone-robotics/tensorflow_catkin/pull/1).

**Comment by 130s** [comment]
@Skydes What's the rationale of closing this without any comments?

**Comment by peci1** [comment]
I think https://github.com/Skydes/tensorflow_catkin/pull/5 ?

**Comment by sarlinpe** [comment]
https://github.com/Skydes/tensorflow_catkin/pull/5 indeed solves the issues.

**Pull request closed without merging**
