### PR TITLE
Update to Tensorflow 1.8

### PR DESCRIPTION
**Pull request by sarlinpe**
Updating to the latest Tensorflow version fixes most of the previous issues. 

I have disabled GRPC (seems redundant with ROS), the Python bindings (better use pip in this case) and all the JPEG- and PNG-related ops (conflicts with OpenCV but can easily be enabled, see the relevant commit). I have also disabled SSE and AVX, the corresponding flags should be set project-wide to avoid alignment issues with Eigen.

The CPU and GPU builds have been tested on Ubuntu 14 and 16.

@peci1 @130s Please let me know if you still encounter any issue.

### CODE REVIEW

**Comment by peci1** [comment]
Thanks, I'll test it in a while ;)

As we found out in https://github.com/tradr-project/tensorflow_ros/pull/7 and https://github.com/tradr-project/tensorflow_ros_cpp/pull/1 , `swig` is also a dependency when compiling TF this way. Could you also add `<build_depend>swig</build_depend>` to the package.xml?

**Comment by peci1** [comment]
Or - maybe when you disabled building the Python parts, maybe swig is no longer needed. I'll try uninstalling it and rebuilding the workspace...

**Comment by sarlinpe** [comment]
Thanks for the feedback! Swig is only required by the Python bindings, so we don't need that dependency anymore.

**Comment by 130s** [comment]
I'm not active on this but @jonlwowski012 is, so he may have some thoughts.

**Comment by peci1** [comment]
On Ubuntu 16.04 it works for me even with swig uninstalled, so it is really no longer a dependency.

**Pull request merged**
